apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wp68szvfi-nodejs
  janus-idp.io/tekton: wp68szvfi-nodejs
  backstage.io/kubernetes-id: wp68szvfi-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wp68szvfi-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
